#!/bin/sh
# sudo apt-get -y install mosquitto-clients
# sudo mcedit /etc/mosquitto/conf.d/mqtt.conf
# mosquitto_pub -h io.adafruit.com -p 1883 -u rpi_home -P $AIO_KEY -t rpi_home/feeds/ifttt -m "message"
clear;
source ~/config.ini;
mosquitto_sub -h io.adafruit.com -p 1883 -u rpi_home -P $AIO_KEY -t rpi_home/feeds/ifttt -R | while read json ; do
echo "`date` => $json"
#awk /^$message/,/^$/ ~/rpi/mc.menu | awk 'NR>1' > run.sh
tmux has-session -t pi:"$json"
if [ "$?" -eq 1 ] ; then tmux new-window -n "$json"; fi
tmux send-keys -t pi:$json "**********$json***********" ENTER
awk /^$json/,/^$/ ~/rpi/mc.menu | awk 'NR>1' > /tmp/"$json".sh
tmux send-keys -t pi:"$json" "sh /tmp/$json.sh" ENTER
tmux select-window -t pi:"$json"
done
