#!/bin/bash

mkdir -p ~/.config/mc
mkdir -p ~/.local/share/mc
ln -sf ~/rpi/mc.menu ~/.config/mc/menu
ln -sf ~/rpi/bashrc ~/.local/share/mc/bashrc
ln -sf ~/rpi/tmux.conf ~/.tmux.conf

if [ ! -d ~/mc.menu ] ; then 
mkdir ~/mc.menu
cd ~/mc.menu
touch "backup" "config" "files" "import" "music" "github"
touch "system" "tools" "videos" "torrent" "photos" "install"
fi


tmux has-session -t pi

if [ "$?" -eq 1 ] ; then

  tmux -u new-session -d -s pi

  tmux rename-window -t pi:1 1
  tmux send '/usr/bin/mc -x /home/pi/rpi/ /media/hdd/' ENTER

  tmux new-window -n 2
  tmux send '/usr/bin/mc -x /home/pi/rpi/ /media/hdd/' ENTER

  tmux new-window -n 3
  tmux send '/usr/bin/mc -x /home/pi/rpi/ /media/hdd/' ENTER

  tmux new-window -n 4
  tmux send '/usr/bin/mc -x /home/pi/rpi/ /media/hdd/' ENTER

  tmux new-window -n 5
  tmux send '/usr/bin/mc -x /home/pi/rpi/ /media/hdd/' ENTER

  tmux new-window -n 6
  tmux send '/usr/bin/mc -x /home/pi/rpi/ /media/hdd/' ENTER

  tmux new-window -n 7
  tmux send '/usr/bin/mc -x /home/pi/rpi/ /media/hdd/' ENTER

  tmux new-window -n 8
  tmux send '/usr/bin/mc -x /media/hdd/Drive/Snoozed /media/hdd/Drive/Documents' ENTER

  tmux new-window -n 9
  tmux send '/usr/bin/mc -x /media/hdd/Drive/Snoozed /media/hdd/Drive/Documents' ENTER

  tmux -u new-session -d -s bg
  tmux switch-client -t bg

  #tmux rename-window -t bg:1 Background
  #tmux set pane-border-format " Bash Background "

fi

tmux select-window -t 1
tmux send -t bg:1 'tmux send -t pi:1 F2' ENTER
tmux attach -t pi:1
