#!/bin/sh
clear
tmux send -t flickr.1 '/home/pi/.bin/flickr-uploader#1/uploadr.py' ENTER
tmux send -t flickr.1 'pushbullet push all note "Flickr#1" "backup finished"' ENTER
tmux select-window -t pi:flickr
tmux select-pane -t flickr.1
tmux -2 attach -t pi
