#!/bin/sh
clear
tmux send -t flickr.2 '/home/pi/.bin/flickr-uploader#2/uploadr.py' ENTER
tmux send -t flickr.2 'pushbullet push all note "Flickr#2" "backup finished"' ENTER
tmux select-window -t pi:flickr
tmux select-pane -t flickr.2
tmux -2 attach -t pi
