#!/bin/sh
clear
rm -rf /home/pi/gdrive/*
cd /home/pi/gdrive/
drive pull --quiet /photos
find /home/pi/gdrive/photos -type d | while read DIR ; do 
echo "$DIR"
done
pushbullet push all note "Raspberry Pi" "Starred Files added to `cat name.csv`"
