#!/bin/sh
clear
sudo mkdir /media/panasonic
sudo mount LABEL=CANON_DC /media/panasonic
mkdir /media/hdd/panasonic
cp -v /media/panasonic/DCIM/???_PANA/*.JPG /media/hdd/panasonic
pushbullet push all note "photos and videos from panasonic are saved"
