#!/bin/bash

tmux has-session -t pi
  if [ "$?" -eq 1 ] ; then
tmux -2 new-session -d -s pi

tmux rename-window -t pi:1 bash
tmux split-window -v
tmux select-pane -t 0

tmux new-window -t pi -a -n cast
tmux split-window -v
tmux select-pane -t 0

tmux new-window -t pi -a -n cloud
tmux split-window -v
tmux select-pane -t 0

tmux new-window -t pi -a -n flickr
tmux split-window -v
tmux select-pane -t 0

tmux new-window -t pi -a -n motion
tmux split-window -v
tmux select-pane -t 0

tmux select-window -t pi:1
fi

tmux -2 attach -t pi
