#!/bin/bash

tmux has-session -t unite
  if [ "$?" -eq 1 ] ; then
tmux -2 new-session -d -s pi
tmux renamewindow -t pi:1 w1
tmux split-window -h
tmux select-pane -t 0
tmux resize-pan -R 30

tmux new-window -t pi -a -n cast
tmux split-window -h
tmux select-pane -t 0
tmux resize-pan -R 30

tmux new-window -t pi -a -n cloud
tmux split-window -h
tmux select-pane -t 0
tmux resize-pan -R 30

tmux new-window -t pi -a -n flickr
tmux split-window -v
tmux select-pane -t 0

tmux new-window -t pi -a -n motion 'ls'
tmux split-window -h
tmux select-pane -t 0
tmux resize-pan -R 30

tmux select-window -t pi:1
tmux -2 attach -t pi

fi
