#!/bin/sh
clear
rm -rf /home/pi/gdrive/*
cd /home/pi/gdrive/
drive pull --quiet Torrents/
find Torrents/*.torrent -type f | while read FILE ; do
torrent $FILE -o /media/hdd/torrents/$FILEwithout torrent extension
done
pushbullet push all note "Raspberry Pi" "All torrents downloaded"
