#!/bin/sh
clear
rm -rf /home/pi/gdrive/*
cd /home/pi/gdrive/
drive pull --quiet Torrents/
find /home/pi/gdrive/Torrents/*.torrent -type f | while read FILE ; do
cd /media/hdd/torrent
torrent "$FILE"
done
pushbullet push all note "Raspberry Pi" "All torrents downloaded"
