#!/bin/sh
clear
curl -o ~/.config/mc/menu https://raw.githubusercontent.com/ManuCart/ServicePi/master/menu
rm ~/service/* 
curl -L -o service.zip https://github.com/ManuCart/ServicePi/archive/master.zip
unzip -jo service.zip -d /home/pi/service ServicePi-master/service/*
rm service.zip
chmod +x ~/service/*
ln -s /media/hdd/Bibliothèques/Musiques/-Scores/ ~/service/play-scores
ln -s /media/hdd/torrent/ ~/service/torrents
ln -s /media/freebox/ ~/service/freebox
ln -s ~/gdrive/ ~/service/gdrive
ln -s ~/.password-store ~/service/passwords
