#!/bin/sh
youtube-dl --ignore-errors --output "/media/hdd/youtube-dl/%(title)s.%(ext)s" https://www.youtube.com/playlist?list=`cat ~/.youtube-dl`
pushbullet push all note "youtube-dl" "Downloads finished"
