#!/bin/sh
clear
tmux has-session -t pi
  if [ "$?" -eq 1 ] ; then
tmux -2 new-session -d -s pi

tmux rename-window -t pi:1 AB
tmux split-window -v

tmux new-window -t pi -a -n CD
tmux split-window -v

tmux new-window -t pi -a -n EF
tmux split-window -v

tmux new-window -t pi -a -n cast
tmux split-window -v
tmux send -t cast.2 'sleep 5' ENTER
tmux send -t cast.2 'bash /home/pi/scripts/mqtt' ENTER

tmux new-window -t pi -a -n cloud
tmux split-window -v

tmux new-window -t pi -a -n merge
tmux split-window -v

tmux select-window -t pi:1
fi

tmux -2 attach -t pi
