#!/bin/sh
#!/bin/sh
sudo mkdir /media/freebox/photos-2048
rsync --archive --no-o --no-g --delete --progress /media/hdd/photos/ /media/freebox/photos-2048
pushbullet push all note "Backup Photos" "Backup finished"
