#!/bin/sh
#~/.bin/picasawebsync.py -d /media/hdd/photos --shrink -m syncUpload --allowDelete remote --override:SAME UPDATE_REMOTE_METADATA --noupdatealbummetadata --purge
~/.bin/picasawebsync.py -d /media/hdd/photos-2048 -m syncUpload --allowDelete remote --purge

~/scripts/iftt-maker "Rasperry Pi" "gplus: Photos sync to family account finished"
