#!/bin/sh
clear
castnow "http://hi5.streamingsoundtracks.com" --type "audio/wav"
#castnow "http://hi.streamingsoundtracks.com" --type "audio/wav"
#castnow "http://hi1.streamingsoundtracks.com:8000" --type "audio/wav"
