#!/bin/sh
# sudo apt-get install imagemagick
# sudo npm install sharp-cli -g
# export NODE_PATH=~/node_modules/
rm ~/test.log
FILES=/media/hdd/photos
#mkdir $FILES
#mkdir /media/hdd/tmp
#rsync --archive --delete --info=progress2 /media/hdd/photos/ $FILES
find $FILES -iname "*.JPG" -type f | sort | while read FILE ; do
  NEWFILE="W`echo "$(basename "$FILE")" | cut -c 2-`"
  echo " ### $FILE"
read H W <<< $(exiv2 -g Exif.Photo.Pixel -Pv "$FILE")
echo " ### $(basename "$FILE") >>> $NEWFILE | $H | $W |"
echo " ### $(basename "$FILE") >>> $NEWFILE | $H | $W |" >> ~/test.log

  #if [ $1 -gt 2048 -o $2 -gt 2048 ] ; then
  #  sharp -i "$FILE" -o /media/hdd/tmp/ resize 2048 2048 --max --withoutEnlargement --withMetadata
  #  rm "$FILE"
  #  mv /media/hdd/tmp/*.JPG "$(dirname "$FILE")/$NEWFILE"
  #else
  #  mv "$FILE" "$(dirname "$FILE")/$NEWFILE"
  #fi
done
#~/scripts/iftt-maker "Backup Photos Web" "Resize Finished"
