#!/bin/sh
# sudo apt-get install imagemagick
# sudo npm install sharp-cli -g
# export NODE_PATH=~/node_modules/
rm ~/test.log
FILES=/media/hdd/photos
#mkdir $FILES
#mkdir /media/hdd/tmp
#rsync --archive --delete --info=progress2 /media/hdd/photos/ $FILES
find $FILES -iname "*.JPG" -type f | sort | while read FILE ; do
  #NEWFILE="W`echo "$(basename "$FILE")" | cut -c 2-`"
  #echo " ### $FILE"
#read H W <<< $(exiv2 -g Exif.Photo.Pixel -Pv "$FILE")
read H x W <<< $(exiv2 "$FILE" | grep "Image size" | cut -d ":" -f 2)

echo " ### $(basename "$FILE") >>> $NEWFILE | $H | $W |"
#echo " ### $(basename "$FILE") >>> $NEWFILE | $H | $W |" >> ~/test.log

  if [ $H -gt 2048 -o $W -gt 2048 ] ; then
  cp "$FILE" /media/hdd/sharp
  fi
done
#~/scripts/iftt-maker "Backup Photos Web" "Resize Finished"
