#!/bin/sh
#Warning Files name does not content comma
clear
GDRIVE=/media/hdd/Drive
rm $GDRIVE/Documents/*
cd $GDRIVE
drive pull --quiet --starred --all
if [ `find $GDRIVE/Documents -type d -empty` ] ; then ~/scripts/iftt-maker "Compress PDF" "ERROR NO DOCUMENTS"; exit ; fi
FILE=`ls $GDRIVE/Documents | head -1`
~/.bin/sejda/bin/sejda-console compress -f Documents/$FILE -o Documents/
mv sejda_out.pdf "Documents/$FILE"
drive push --quiet "Documents/$FILE"
drive unstar --quiet "Documents/$FILE"
~/scripts/iftt-maker "Raspberry Pi" "File $FILE compressed"
