#!/bin/sh
# ls -l /dev/disk/by-id 
ID="/dev/disk/by-id/usb-MATSHITA_DMC-TZ40_0000000000000000000F1104040931-0:0-part1"
PHOTOS="/media/hdd/Drive/Camera"
TMP="/media/hdd/tmp"
clear
sudo mkdir /media/panasonic
sudo mount $ID /media/panasonic
mkdir $TMP
mkdir $PHOTOS
cp -v /media/panasonic/DCIM/???_PANA/*.JPG $TMP
sudo umount /media/panasonic

find $TMP -iname "*.jpg" -type f | while read FILE ; do 
EXIF=`exiv2 "$FILE" 2> null | grep "Image timestamp" | cut -d ' ' -f 4 | tr ':' '-'`
YEAR=`echo "$EXIF" | cut -d '-' -f 1`
if [ ! -d "$PHOTOS/$YEAR" ]; then mkdir "$PHOTOS/$YEAR"; fi
if [ ! -d "$PHOTOS/$YEAR/$EXIF" ]; then mkdir "$PHOTOS/$YEAR/$EXIF"; fi
mv -v $FILE $PHOTOS/$YEAR/$EXIF/$(basename $FILE)
done
rm -r $TMP

cd /media/hdd/Drive
drive push --quiet Camera/*

pushbullet push all note "photos and videos from panasonic are saved"
