#!/bin/sh
# ls -l /dev/disk/by-id 
ID="/dev/disk/by-id/usb-MATSHITA_DMC-TZ40_0000000000000000000F1104040931-0:0-part1"
VIDEOS="/media/hdd/youtube-upload"
clear
sudo mkdir /media/panasonic
sudo mount $ID /media/panasonic
cp -v /media/panasonic/DCIM/???_PANA/*.MP4 $VIDEOS
~/scripts/iftt-maker "All videos from Camera are copied"
