#!/bin/sh
usbmuxd
VIDEOS="/media/hdd/youtube-upload"
clear
sudo mkdir /media/iphone
idevicepair pair
sudo ifuse /media/iphone
rsync --archive --info=progress2 /media/iphone/ $VIDEOS
sudo umount /media/iphone
~/scripts/iftt-maker "All videos from usbkey are copied"
