#!/bin/sh
# ls -l /dev/disk/by-id 
ID="/dev/disk/by-id/usb-Kingston_DataTraveler_3.0_08606E6D3FDEBF602707123F-0:0-part1"
VIDEOS="/media/hdd/youtube-upload"
clear
sudo mkdir /media/usbkey
sudo mount $ID /media/usbkey
rsync --archive --info=progress2 /media/usbkey/ $VIDEOS
sudo umount /media/usbkey
~/scripts/iftt-maker "All videos from usbkey are copied"
