#!/bin/sh
usbmuxd
VIDEOS="/media/hdd/youtube-upload"
clear
sudo mkdir /media/iphone
sudo umount /media/iphone
echo "Please connect iphone, accept the connection and enter password"
read -e -p "Press any key to continue..." key
idevicepair pair
sudo ifuse /media/iphone
sudo rsync --include '*/' --include '*.MOV' --exclude '*' --archive --info=progress2 /media/iphone/DCIM/100APPLE/ $VIDEOS
sudo chown -R pi:pi $VIDEOS
~/scripts/iftt-maker "All videos from usbkey are copied"
