#!/bin/sh
# Create .mqtt files with
#echo '/a/<API_ID>/p/<PROJECT>/d/<UUID>/#' | tee ~/.mqtt
# or copy from https://gist.github.com/ManuCart
#tmux new-window -t pi -a -n flickr

mosquitto_sub -h mqtt.devicehub.net -p 1883 -t "`cat ~/.mqtt`" -R | while read val; do
echo $val
a=`echo "$val" |  jq '.["state"]' -r`
echo $a
    case $val in
    merge)
	echo "==> merge"
	cd ~/scripts && clear
	bash merge-pdf
	;;
    cast)
	echo "cast ALERT: ${val}"
	;;
    esac
done
