#!/bin/sh
#sudo mcedit /etc/mosquitto/conf.d/mqtt.conf
#>connection cloudmqtt
#>address <Instance Server>:<Instance Port>
#>remote_username <Instance User>
#>remote_password <Instance Password>
#>clientid <A cloudmqtt user with read access>
#>try_private false
#>start_type automatic

#sudo /etc/init.d/mosquitto restart

mosquitto_sub -h m21.cloudmqtt.com -p 19083 -u pi -P raspberry -t script -R | while read valeur ; do
a=`echo "$valeur"

echo "--------receive $a"

if [ ! -f ~/scripts/$a ] ; then
  #pushbullet push all note "$a not exist"
  echo "ERROR script $a not exist"
  else

    tmux has-session -t $a
    if [ "$?" -eq 1 ] ; then
    tmux set-environment -g a $a
    TMUX= tmux -2 new-session -d -s $a
    fi

    if flock -n /tmp/$a false ; then 
    #pushbullet push all note "$a locked"
    echo "$a locked"
    else
    echo "$a running"
    tmux send -t $a 'pushbullet push all note "$a..."' ENTER
    tmux send -t $a 'flock -xn /tmp/$a.lck -c ~/scripts/$a' ENTER
    tmux send -t $a '#tmux kill-session -t $a' ENTER
    fi

fi
done
