#!/bin/sh
# Create .mqtt files with
# echo '/a/<API_ID>/p/<PROJECT>/d/<UUID>/#' | tee ~/.mqtt

mosquitto_sub -h mqtt.devicehub.net -p 1883 -t "`cat ~/.mqtt`" -R | while read valeur ; do
a=`echo "$valeur" |  jq '.["value"]' -r`

tmux has-session -t $a
if [ "$?" -eq 1 ] ; then
tmux set-environment -g a $a
TMUX= tmux -2 new-session -d -s $a
fi

tmux send -t $a 'pushbullet push all note "$a" "$a script starting"' ENTER
tmux send -t $a '~/scripts/$a' ENTER
tmux send -t $a '#tmux kill-session -t $a' ENTER

done
