#!/bin/bash
## TODO Delete only files merged

ansi --bg-yellow-intense --newline " ### `date` ###"
GDRIVE=/media/hdd/Drive
FILE=/home/pi/ifttt.csv

#Init
cd $GDRIVE

ansi --bg-blue --newline "### Download Snoozed Dir ###"
#rm -rf Snoozed
if ! drive pull --no-prompt -fix-clashes "Snoozed/"; then ~/scripts/iftt-maker "Auto Merge PDF" "Error pull, please fix clashes in Snoozed folder"; exit; fi

ansi --bg-blue --newline "### Test if Snoozed Dir Empty###"
if [ `find "Snoozed" -type d -empty` ] ; then echo " ### Empty directory ### "; exit; fi

ansi --bg-blue --newline "### Download ifttt ###"
if ! drive pull --no-prompt --export csv --exports-dir /tmp --same-exports-dir --force ifttt; then ~/scripts/iftt-maker "Auto Merge PDF" "Error pull for ifttt.xls" ; exit; fi
tr -d '\r' < /tmp/ifttt.csv > $FILE


#Download
ansi --bg-blue --newline "### read ifttt.csv ###"

while IFS=, read email in out ; do
    echo "I got:|$email|$in|$out|"    
    if [[ -n $(find "Snoozed" -name "$in") ]]
        then
        rm ~/files.csv
        echo " ### Find : $in do run merge"
        find "Snoozed" -name "$in" | sort -r | tr '\n' ',' > ~/files.csv
        cp ~/files.csv ~/files_rm.csv
        echo "Snoozed/$out" >> ~/files.csv
        ansi --bg-red --newline "cat ~/files.csv"
        cat ~/files.csv
        ansi --bg-red --newline "####END####"
        #if ! drive pull --no-prompt "Documents/$out" ; then ~/scripts/iftt-maker "Auto Merge PDF" "Error pull ref doc" ; exit; fi
        #cp "Documents/$out" "Ifttt/$out"
        #if grep -r "Encrypt" Ifttt ; then ~/scripts/iftt-maker "Auto Merge PDF" "ERROR CRYPTED FILE"; exit; fi
        #~/.bin/sejda/bin/sejda-console merge -l ~/files.csv -o sejda_out.pdf
        #mv sejda_out.pdf "Documents/$out"
        #if ! drive push --no-prompt "Documents/$out" ; then ~/scripts/iftt-maker "Auto Merge PDF" "Error push ref doc" ; exit; fi
        #while IFS=, read f ; do
        #echo "#### $f ### to delete"
        #done < ~/files_rm.csv
    fi
done < "$FILE"

rm $FILE
rm IFTTT/*
