#!/bin/sh
clear

rm -rf /media/hdd/Drive/Photos/*
cd /media/hdd/Drive
drive pull --quiet --starred --all

find /media/hdd/Drive/Photos -iname "*.jpg" -type f | sort | while read FILE ; do 
echo "$FILE"
NEWDATE=`echo "$(dirname "$FILE")" | rev | cut -d '/' -f 1 | rev | cut -d ' ' -f  1 | tr '-' ':'`
exiv2 delete "$FILE"
exiv2 -M "add Exif.Photo.DateTimeOriginal $NEWDATE 00:00:00" "$FILE"
echo "eviv2 end formatting"
drive push --quiet "$FILE"
done



#drive pull --quiet Photos
#rsync -a --ignore-existing --remove-source-files --progress /media/hdd/Drive/photos/ /media/hdd/photos
#pushbullet push all note "Raspberry Pi" "Done"
#drive trash Photos
#rm -rf /media/hdd/Drive/Photos
