#!/bin/sh
clear
rm -rf /media/hdd/Drive/Photos/*
cd /media/hdd/Drive
drive pull --quiet Photos
rsync -a --ignore-existing --remove-source-files --progress /media/hdd/Drive/Photos/ /media/hdd/photos
find /media/hdd/Drive/Photos/ -type d -empty -delete
drive push --quiet Photos
~/scripts/iftt-maker "Raspberry Pi" "Done"
