#!/bin/sh
#Check only starred photos
clear
rm -rf /media/hdd/Drive/Photos/*
cd /media/hdd/Drive
if ! drive pull --quiet --starred --all ; then pushbullet push all note "ERROR DRIVE" "ERROR PULL DRIVE"; exit; fi
find /media/hdd/Drive/Photos -iname "*.jpg" -type f | sort | while read FILE ; do 
echo "$FILE"
NEWDATE=`echo "$(dirname "$FILE")" | rev | cut -d '/' -f 1 | rev | cut -d ' ' -f  1 | tr '-' ':'`
# A faire si besoin
# exiv2 delete "$FILE"
exiv2 -M "add Exif.Photo.DateTimeOriginal $NEWDATE 00:00:00" "$FILE"
echo "eviv2 end formatting"
drive push --quiet "$FILE"
drive unstar "$FILE"
done
pushbullet push all note "Raspberry Pi" "Done"
