#!/bin/sh
#Warning Files name does not content comma
clear
GDRIVE=/media/hdd/Drive
rm $GDRIVE/Snoozed/*
rm $GDRIVE/Documents/*
cd $GDRIVE
if ! drive pull --no-prompt --starred --all ; then ~/scripts/iftt-maker "Merge PDF" "Error pull starred" ; exit; fi
if [ `find $GDRIVE/Documents -type d -empty` ] ; then ~/scripts/iftt-maker note "Merge PDF" "ERROR NO DOCUMENTS"; exit ; fi
if grep -r "Encrypt" $GDRIVE/Snoozed ; then ~/scripts/iftt-maker "Merge PDF" "ERROR CRYPTED FILE"; exit; fi
find $GDRIVE/Snoozed -type f | sort | tr '\n' ',' > files.csv
find $GDRIVE/Documents -type f | head -1  >> files.csv
FILE=`ls $GDRIVE/Documents | head -1`
if [ -f files.csv ] ; then ~/.bin/sejda/bin/sejda-console merge -l files.csv -o sejda_out.pdf ; fi
mv sejda_out.pdf "Documents/$FILE"
if ! drive push --no-prompt "Documents/$FILE" ; then ~/scripts/iftt-maker "Merge PDF" "Error push document" ; exit; fi
drive unstar --no-prompt "Documents/$FILE"
drive trash --starred
~/scripts/iftt-maker "Raspberry Pi" "Starred Files added to $FILE"
