#!/bin/sh
clear
GDRIVE=/media/hdd/Drive
rm -rf $GDRIVE/*
cd $GDRIVE
drive pull --quiet --starred --all
if grep -r "Encrypt" $GDRIVE/Snoozed ; then pushbullet push all note "Merge PDF" "ERROR CRYPTED FILE"; exit; fi
find $GDRIVE/Snoozed -type f | sort | tr '\n' ',' > files.csv
find $GDRIVE/Documents -type f | head -1  >> files.csv
ls $GDRIVE/Documents | head -1 > name.csv
if [ -f files.csv ] ; then ~/.bin/sejda/bin/sejda-console merge -l files.csv -o sejda_out.pdf ; fi
mv sejda_out.pdf "Documents/`cat name.csv`"
drive push --quiet "Documents/`cat name.csv`"
drive unstar --quiet "Documents/`cat name.csv`"
pushbullet push all note "Raspberry Pi" "Starred Files added to `cat name.csv`"
