#!/bin/sh
clear
GDRIVE=/media/hdd/Drive
rm $GDRIVE/Snoozed/*
rm $GDRIVE/Documents/*
cd $GDRIVE
drive pull --quiet --starred --all
if grep -r "Encrypt" $GDRIVE/Snoozed ; then pushbullet push all note "Merge PDF" "ERROR CRYPTED FILE"; exit; fi
find $GDRIVE/Snoozed -type f | sort | tr '\n' ',' > files.csv
find $GDRIVE/Documents -type f | head -1  >> files.csv
FILE=`ls $GDRIVE/Documents | head -1`
if [ -f files.csv ] ; then ~/.bin/sejda/bin/sejda-console merge -l files.csv -o sejda_out.pdf ; fi
mv sejda_out.pdf "Documents/$FILE"
drive push --quiet "Documents/$FILE"
drive unstar --quiet "Documents/$FILE"
for f in `cat files.csv`
do
  echo $f
done
pushbullet push all note "Raspberry Pi" "Starred Files added to `cat name.csv`"
