#!/bin/sh
#sudo mcedit /etc/mosquitto/conf.d/mqtt.conf
#>connection cloudmqtt
#>address <Instance Server>:<Instance Port>
#>remote_username <Instance User>
#>remote_password <Instance Password>
#>clientid <A cloudmqtt user with read access>
#>try_private false
#>start_type automatic
#>topic # in
#sudo /etc/init.d/mosquitto restart
echo "log script tag" > /tmp/mqtt.log
mosquitto_sub -h m21.cloudmqtt.com -p 19083 -u pi -P raspberry -t script -R | while read message ; do
echo "$date - $message" >> /tmp/mqtt.log
wall $message
case $message in
  m)
    /home/pi/scripts/solo -port=6001 /home/pi/scripts/$message;;
  
  p)
    wall "debut de srare now"
    tmux has-session -t pi ; if [ "$?" -eq 1 ] ; then ~/scripts/!tmux ; fi
    tmux send -t cast.1 'cd ~/scripts && clear' ENTER
    tmux send -t cast.1 'castnow-start' ENTER
    tmux select-window -t pi:cast
    tmux select-pane -t cast.1
    wall "(((((((((((((((((((((((((("
    tmux attach -t pi;;
  
  
  
  s)
    wall "debut de srare now"
    tmux has-session -t pi ; if [ "$?" -eq 1 ] ; then ~/scripts/!tmux ; fi
    tmux send -t cast.1 'cd ~/scripts && clear' ENTER
    tmux send-keys -t cast.1 C-r
    tmux send -t cast.1 'castnow-stop' ENTER
    tmux select-window -t pi:cast
    tmux select-pane -t cast.1
    wall "(((((((((((((((((((((((((("
    tmux attach -t pi;;
  
  *) ;;
esac
done
