#!/bin/sh
#sudo mcedit /etc/mosquitto/conf.d/mqtt.conf
#>connection cloudmqtt
#>address <Instance Server>:<Instance Port>
#>remote_username <Instance User>
#>remote_password <Instance Password>
#>clientid <A cloudmqtt user with read access>
#>try_private false
#>start_type automatic
#>topic # in
#sudo /etc/init.d/mosquitto restart
echo "log script tag" > /tmp/mqtt.log
mosquitto_sub -h m21.cloudmqtt.com -p 19083 -u pi -P raspberry -t script -R | while read message ; do
echo "$date - $message" >> /tmp/mqtt.log
wall $message
case $message in
  merge-pdf)
    /home/pi/scripts/solo -port=6001 /home/pi/scripts/$message;;
  
  castnow-start)
    wall "debut de srare now"
    tmux send -t AB.1 'cd ~/scripts && clear' ENTER
    tmux send -t AB.1 '/home/pi/scripts/solo -port=6002 /home/pi/scripts/castnow-start' ENTER
    tmux select-window -t pi:AB
    tmux select-pane -t AB.1
    tmux -2 attach -t pi;;
  
  castnow-stop)
    /home/pi/scripts/solo -port=6003 /home/pi/scripts/$message;;
  
  *) ;;
esac
done
