#!/bin/sh
#sudo mcedit /etc/mosquitto/conf.d/mqtt.conf
#>connection cloudmqtt
#>address <Instance Server>:<Instance Port>
#>remote_username <Instance User>
#>remote_password <Instance Password>
#>clientid <A cloudmqtt user with read access>
#>try_private false
#>start_type automatic
#>topic # in
#sudo /etc/init.d/mosquitto restart
echo "log script tag" > /tmp/mqtt.log
mosquitto_sub -h m21.cloudmqtt.com -p 19083 -u pi -P raspberry -t script -R | while read message ; do

echo "$message" >> /tmp/mqtt.log

if [ ! -f ~/scripts/$message ] ; then
  echo "ERROR script $message not exist" >> /tmp/mqtt/log
  else

    tmux has-session -t $message
    if [ "$?" -eq 1 ] ; then
    tmux set-environment -g a $message
    TMUX= tmux -2 new-session -d -s $message
    fi

    if flock -n /tmp/$message false ; then 
    #pushbullet push all note "$a locked"
    echo "$message locked" >> /tmp/mqtt/log
    else
    echo "$message running" >> /tmp/mqtt/log
    tmux send -t $message 'pushbullet push all note "$a..."' ENTER
    tmux send -t $message 'flock -xn /tmp/$a.lck -c ~/scripts/$a' ENTER
    tmux send -t $message '#tmux kill-session -t $a' ENTER
    fi

fi
done
