#!/bin/sh

  FILES=/media/hdd/photos
  #FILES=/media/hdd/photos-web
  if [ ! -f /usr/bin/exiv2 ]; then ~/scripts/iftt-maker "Rasperry Pi" "ERROR: Please install exiv2"; exit; fi
  
  # Loop through directories, delete empty directories
  find $FILES -type d -empty -delete
  
  # Loop through files, renaming each to a YYYYMMDDHHMMSS-######.JPG based name
  COUNTER=1
  find $FILES -iname "*.jpg" -type f | sort | while read FILE ; do
    EXIF=`exiv2 "$FILE" 2> null | grep "Image timestamp" | cut -d ' ' -f 4,5 | tr -d ':' | tr -d ' '`
    NEWFILE="$EXIF-$(printf '%06d' $COUNTER).JPG"
    echo "`basename "$FILE"`=>$NEWFILE"
    touch -t ${EXIF:0:12}.${EXIF:12:13} "$FILE"
    mv -u "$FILE" "`dirname "$FILE"`/$NEWFILE"
    COUNTER=$((COUNTER + 1))
  done
  
  # Loop again through files, renaming as "P2######.JPG"
  COUNTER=1
  find $FILES -iname "*.jpg" -type f | sort | while read FILE ; do 
    NEWNAME="P2$(printf "%06d" $COUNTER).JPG"
    #NEWNAME="W1$(printf "%06d" $COUNTER).JPG"
    mv "$FILE" "`dirname "$FILE"`/$NEWNAME"
    COUNTER=$((COUNTER + 1))
  done
  
   # Loop through directories and change creating date
  find $FILES -type d | while read DIR ; do
  DAT=`echo "$DIR" | rev | cut -d '/' -f 1 | rev | cut -d ' ' -f  1 | tr -d '-'`
  if [ ${#DAT} == 4 ]; then DAT=`echo "${DAT}0101"` ; fi
  touch -t "${DAT}0000.00" "$DIR"
  done
  
  ~/scripts/iftt-maker "Rasperry Pi" "Photos Renamer Done"
