#!/bin/sh
#Check only starred photos
#Be carefoul this script delete entire exif file
GOOGLE_PHOTOS_DIR="/media/hdd/Drive/Google Photos"
clear
rm -rf "$GOOGLE_PHOTOS_DIR/"*
cd /media/hdd/Drive
if ! drive pull --yes --starred --all ; then ~/scripts/iftt-maker "Raspberry Pi - Photos Step 2" "ERROR PULL DRIVE"; exit; fi

find "$GOOGLE_PHOTOS_DIR" -iname "*.jpg" -type f | sort | while read FILE ; do 
echo "$FILE"
NEWDATE=`echo "$(dirname "$FILE")" | rev | cut -d '/' -f 1 | rev | cut -d ' ' -f  1 | tr '-' ':'`
exiv2 delete "$FILE"
exiv2 -M "add Exif.Photo.DateTimeOriginal $NEWDATE 00:00:00" "$FILE"
echo "eviv2 end formatting"
if ! drive push --yes "$FILE" ; then ~/scripts/iftt-maker "Raspberry Pi - Photos Step 2" "ERROR PUSH DRIVE"; exit; fi
drive unstar "$FILE"
done

~/scripts/iftt-maker "Raspberry Pi - Photos Step 2" "Done"
