#!/bin/sh

GOOGLE_PHOTOS_DIR="/media/hdd/Drive/Google Photos"
BACKUP_DIR="/media/hdd/backup"
clear

#Copy from Google Photos
if [ ! -f /usr/bin/exiv2 ] ; then ~/scripts/iftt-maker "Rasperry Pi - Photos Step 1" "ERROR: Please install exiv2"; exit; fi
cd /media/hdd/Drive/
if ! drive pull --no-prompt "Google Photos" ; then ~/scripts/iftt-maker "Rasperry Pi - Photos Step 1" "ERROR PULL DRIVE"; exit; fi

#Backup
mkdir "$BACKUP_DIR"
rsync --archive --delete --info=progress2 "$GOOGLE_PHOTOS_DIR" "$BACKUP_DIR"

#
find "$GOOGLE_PHOTOS_DIR" -iname "*.jpg" -type f | sort | while read FILE ; do 
EXIF=`exiv2 "$FILE" 2> null | grep "Image timestamp" | cut -d ' ' -f 4 | tr ':' '-'`
EXIF1=`echo "$EXIF" | cut -d '-' -f 1,2 | tr '-' ' '`

  if [ -z "$EXIF1" ]; then
    NEWDATE=`echo "$(dirname "$FILE")" | rev | cut -d '/' -f 1 | rev | cut -d ' ' -f  1 | tr '-' ':'`
    exiv2 -M "add Exif.Photo.DateTimeOriginal $NEWDATE 00:00:00" "$FILE"
    sleep 1
    EXIF=`exiv2 "$FILE" 2> null | grep "Image timestamp" | cut -d ' ' -f 4 | tr ':' '-'`
    EXIF1=`echo "$EXIF" | cut -d '-' -f 1,2 | tr '-' ' '`
  fi
  
  if [ -z "$EXIF1" ]; then
    exiv2 delete "$FILE"
    exiv2 -M "add Exif.Photo.DateTimeOriginal $NEWDATE 00:00:00" "$FILE"
    EXIF=`exiv2 "$FILE" 2> null | grep "Image timestamp" | cut -d ' ' -f 4 | tr ':' '-'`
    EXIF1=`echo "$EXIF" | cut -d '-' -f 1,2 | tr '-' ' '`
  fi

EXIF2=`date -d "$EXIF -1 month" +"%Y %m"`
EXIF3=`date -d "$EXIF +1 month" +"%Y %m"`
DAT=`echo "$(dirname "$FILE")" | rev | cut -d '/' -f 1 | rev | cut -d ' ' -f  1 | cut -d '-' -f 1,2 | tr '-' ' '`

  if [ "$DAT" != "$EXIF1" ] && [ "$DAT" != "$EXIF2" ] && [ "$DAT" != "$EXIF3" ]; then
    mv -u "$FILE" "$(dirname "$FILE")/Google Photos $(basename "$FILE")"
  fi

printf "\033[00m$FILE\n\033[01mEXIF:$EXIF EXIF1:$EXIF1 EXIF2:$EXIF2 EXIF3:$EXIF3 DATE:$DAT\n"
done

### Copy to HDD photos
rsync -a --ignore-existing --remove-source-files --progress "$GOOGLE_PHOTOS_DIR" "/media/hdd/photos"
find "$GOOGLE_PHOTOS_DIR" -type d -empty -delete
drive push --no-prompt "Google Photos"

## Backup to freebox
sudo mkdir /media/freebox
sudo mount -t cifs //mafreebox.freebox.fr/Server\ Freebox/  /media/freebox -o user=freebox,password=mini4K,uid=1000,gid=1000,rw,sec=ntlm
rsync --archive --no-o --no-g --delete --info=progress2 /media/hdd/photos/ /media/freebox/photos
PHOTOS_DIR=/media/hdd/photos
  
## Rename Photos 
  # Loop through directories, delete empty directories
  find $PHOTOS_DIR -type d -empty -delete
  
  # Loop through files, renaming each to a YYYYMMDDHHMMSS-#####.JPG based name
  COUNTER=1
  find $PHOTOS_DIR -iname "*.jpg" -type f | sort | while read FILE ; do
    EXIF=`exiv2 "$FILE" 2> null | grep "Image timestamp" | cut -d ' ' -f 4,5 | tr -d ':' | tr -d ' '`
    NEWFILE="$EXIF-$(printf '%05d' $COUNTER).JPG"
    echo "`basename "$FILE"`=>$NEWFILE"
    touch -t ${EXIF:0:12}.${EXIF:12:13} "$FILE"
    mv -u "$FILE" "`dirname "$FILE"`/$NEWFILE"
    COUNTER=$((COUNTER + 1))
  done
  
  # Loop again through files, renaming as "IMG_#####.JPG"
  COUNTER=1
  find $PHOTOS_DIR -iname "*.jpg" -type f | sort | while read FILE ; do 
    NEWNAME="IMG_$(printf "%05d" $COUNTER).JPG"
    mv "$FILE" "`dirname "$FILE"`/$NEWNAME"
    COUNTER=$((COUNTER + 1))
  done
  
   # Loop through directories and change creating date
  find $PHOTOS_DIR -type d | while read DIR ; do
  DAT=`echo "$DIR" | rev | cut -d '/' -f 1 | rev | cut -d ' ' -f  1 | tr -d '-'`
  if [ ${#DAT} == 4 ]; then DAT=`echo "${DAT}0101"` ; fi
  touch -t "${DAT}0000.00" "$DIR"
  done

