#!/bin/sh
GOOGLE_PHOTOS_DIR="/media/hdd/Drive/Google Photos"
PHOTOS_DIR="/media/hdd/photos"
COUNTER=`ls $PHOTOS_DIR -R -v | tail -n 1 | cut -d '.' -f  1 | cut -c 3-`
COUNTER=$((COUNTER + 1))
NEWNAME="P1$(printf "%06d" $COUNTER).JPG"
echo $NEWNAME
