#!/bin/sh
#~/.bin/picasawebsync.py -d /media/hdd/photos-web -m syncUpload --allowDelete remote --noupdatealbummetadata --purge -c7
~/.bin/picasawebsync.py -d /media/hdd/photos-web -m syncUpload --allowDelete remote --purge

~/scripts/iftt-maker "Rasperry Pi" "gplus: Photos sync to family account finished"
