#!/bin/sh
FILES=/media/hdd/photos-2048
#mkdir $FILES
#rsync --archive --delete --info=progress2 /media/hdd/photos/ $FILES
find $FILES -iname "*.JPG" -type f | sort | while read FILE ; do
  c=`identify -format "%w %h" "$FILE"`
  set $c
  if [ $1 -gt 2048 -o $2 -gt 2048 ] ; then 
    sharp --verbose --max --width 2048 --height 2048 --withoutEnlargement -o "$FILE" "$FILE"
    #mogrify -format jpg -verbose -auto-orient -resize 2048x2048 -quality 100% "$FILE"
  fi
done
pushbullet push all note "Backup Photos 2048" "Resize Finished"
