#!/bin/sh
# sudo apt-get install imagemagick
# sudo npm install sharp-cli -g
# export NODE_PATH=~/node_modules/
FILES=/media/hdd/photos-web
mkdir $FILES
rsync --archive --delete --info=progress2 /media/hdd/photos/ $FILES
find $FILES -iname "*.JPG" -type f | sort | while read FILE ; do
  echo "$FILE"
  c=`identify -format "%w %h" "$FILE"`
  set $c
  if [ $1 -gt 2048 -o $2 -gt 2048 ] ; then 
    sharp --verbose --max --width 2048 --height 2048 --withoutEnlargement -o "$FILE" "$FILE"
  fi
done
~/scripts/iftt-maker "Backup Photos Web" "Resize Finished"
