#!/bin/sh

  FILES=/media/hdd/photos
  
  if [ ! -f /usr/bin/exiv2 ]; then pushbullet push all note "Rasperry Pi" "ERROR: Please install exiv2"; exit; fi
  
  # Loop through directories, delete empty directories
  find $FILES -type d -empty -delete
  
  # Loop through files, renaming each to a YYYYMMDDHHMMSS-#####.JPG based name
  COUNTER=1
  find $FILES -iname "*.jpg" -type f | sort | while read FILE ; do
    EXIF=`exiv2 "$FILE" 2> null | grep "Image timestamp" | cut -d ' ' -f 4,5 | tr -d ':' | tr -d ' '`
    NEWFILE="$EXIF-$(printf '%05d' $COUNTER).JPG"
    echo "`basename "$FILE"`=>$NEWFILE"
    echo "${EXIF:0:12}.${EXIF:12:13} $FILE"
    #touch -t ${EXIF:0:12}.${EXIF:12:13} "$FILE"
    #mv -u "$FILE" "`dirname "$FILE"`/$NEWFILE"
    COUNTER=$((COUNTER + 1))
  done
  
 
  pushbullet push all note "Rasperry Pi" "Photos Renamer Done"
