#!/bin/sh
#
#  This script sends whatever is piped to it as a message to the specified Telegram bot
#
source ~/config.ini

# example:
# apiToken=123456789:AbCdEfgijk1LmPQRSTu234v5Wx-yZA67BCD
# userChatId=123456789

if [ -z "$1" ] ; then
        echo "Please give a picture link"
else
        curl -s \
        -X POST \
        https://api.telegram.org/bot$apiToken/sendPhoto \
        -d photo="$1" \
        -d chat_id=$userChatId
echo ""
fi
