#!/bin/sh

sudo sed -ie '$d' /etc/transmission-daemon/settings.json
cat << EOF | sudo tee -a /etc/transmission-daemon/settings.json
,
"proxy": "localhost",
"proxy-auth-enabled": false,
"proxy-auth-password": "",
"proxy-auth-username": "",
"proxy-enabled": true,
"proxy-port": 8080,
"proxy-type": 0
}
EOF

cd /media/hdd/Drive
drive pull --quiet RaspberryPi/bittoratio3.py
mv RaspberryPi/bittoratio3.py ~/bittoratio3.py
cd ~
mcedit bittoratio3.py
# change FACTOR & PORT
python bittoratio3.py &&
sudo service transmission-daemon restart
