#!/bin/sh
clear
mkdir ~/scripts/
cd ~
rm  ~/scripts.zip
curl -o ~/.config/mc/menu https://raw.githubusercontent.com/ManuCart/RaspberryPi/master/menu
rm ~/scripts/* 
curl -L -o scripts.zip https://github.com/ManuCart/raspberrypi/archive/master.zip
unzip -jo scripts.zip -d ~/scripts RaspberryPi-master/scripts/*
chmod +x ~/scripts/*
ln -s /media/hdd/torrents/ ~/scripts/torrents
ln -s /media/hdd/ ~/scripts/hdd
ln -s /media/hdd/Drive/ ~/scripts/drive
ln -s /media/freebox/ ~/scripts/freebox
