#!/bin/sh
# echo "<<id>>" > ~/.youtube.dl
sudo apt-get -y install libavcodec-extra libav-tools
mkdir /media/hdd/youtube-dl
youtube-dl --ignore-errors --format 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo+bestaudio' --merge-output-format mp4 --output "/media/hdd/youtube-dl/%(title)s.%(ext)s" https://www.youtube.com/playlist?list=`cat ~/.youtube-dl`
while exist /media/hdd/youtube-dl/*.part
do 
youtube-dl --ignore-errors --format 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo+bestaudio' --merge-output-format mp4 --output "/media/hdd/youtube-dl/%(title)s.%(ext)s" https://www.youtube.com/playlist?list=`cat ~/.youtube-dl`
done
~/scripts/iftt-maker "youtube-dl" "Downloads finished"
