#!/bin/sh
# echo "<<id>>" > ~/.youtube.dl
mkdir /media/hdd/youtube-dl
youtube-dl --ignore-errors --format bestaudio+bestvideo --output "/media/hdd/youtube-dl/%(title)s.%(ext)s" https://www.youtube.com/playlist?list=`cat ~/.youtube-dl`
pushbullet push all note "youtube-dl" "Downloads finished"
